[env]
CARGO_MAKE_RUST_TARGET_TRIPLE = "wasm32-unknown-unknown"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build-wasm]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.wasm-bindgen]
install_crate = "wasm-bindgen-cli"
command = "wasm-bindgen"
args = ["target/wasm32-unknown-unknown/debug/hello_wasm.wasm", "--out-dir=./pkg", "--target=web"]
dependencies = ["build-wasm"]

[tasks.build]
dependencies = ["wasm-bindgen"]

[tasks.run]
command = "python"
args = ["./httpserver.py"]
dependencies = ["build"]